### ISSUE TITLE
Implement 8-bit color graphics

### ISSUE THREAD

**Issue by cspang1** [cspang1/JCAP#57]
Based on research performed for issue #54.

**Comment by cspang1** [comment]
Narrowed problem down to horizontal back porch race condition + doubling each visible scanline.

**Comment by cspang1** [comment]
Satisfied by commit 65eeeba70623c0ccc433b47d05c13f2bce0cef38

**Comment by cspang1** [comment]
@konimaru the fruits of your labor haha:

[![IT'S ALIVE!](https://img.youtube.com/vi/JxgBV34brZk/0.jpg)](https://www.youtube.com/watch?v=JxgBV34brZk)

**Comment by konimaru** [comment]
Cool stuff! Glad I could be of assistance.
