### ISSUE TITLE
Determine EEPROM Writing Solution

### ISSUE THREAD

**Issue by cspang1** [cspang1/JCAP#76]
This is looking somewhat further down the proverbial development road.

I will be using a [1Mbit SPI EEPROM](https://www.mouser.com/ProductDetail/Microchip-Technology/25LC1024-I-P?qs=sGAEpiMZZMuVhdAcoizlRS6kJF9v8jHR8McwQZNv8N0%3D) for static game resource storage (tile map, tile/sprite pixel palettes, tile/sprite color palettes), which would allow for ~50 full tile maps worth of canvas. This data will be loaded into a [1Mbit SPI SRAM](https://www.microchip.com/datasheet/23LC1024) at system instantiation.

The question is: what's a reasonable way to load 128K worth of data into the EEPROM, when the Propeller can only handle 32K at programming time. Should an in-circuit programmer be used? Should some shenanigans be implemented to load the data piecemeal via the Propeller? Should the data be sent serially to the Prop via the Prop Plug and stored one at a time?

I'm certain there is a best practice well accepted solution to this, but nothing is really popping out in my searches.

Ideally the solution would be one-click, as during game development the graphics resources would be constantly updated and tested, so if there's a solution that wouldn't require overwriting the boot EEPROM of the Propeller (so as not to overwrite the CPU code itself, necessitating a re-load) or even better wouldn't require the Prop at all, it would be ideal.

**Comment by cspang1** [comment]
[Looks like Macca was investigating this exact same problem](http://forums.parallax.com/discussion/162274/large-read-only-data-tables), but doesn't seem to really elaborate on his solution - plus it looks like he's using a C compiled solution.

**Comment by konimaru** [comment]
There is the Hydra-Asset-Manager (HAM). It needs some tweaking (the back end on the P1) but worked fine for me in the past. I believe up to 128MB was possible.

[HAM_1_09.zip](https://github.com/cspang1/JCAP/files/3213584/HAM_1_09.zip)

**Comment by cspang1** [comment]
Outstanding - any elaboration for "tweaks on the back end"?

**Comment by konimaru** [comment]
The original backend used the TV driver + the Graphics object. I commented that out. I believe you have the tweaked version already in that archive.

**Comment by cspang1** [comment]
Oh nice. I'm thinking though... the Propeller's boot EEPROM is I2C, but the ones I'm attempting to write to are SPI - so I'll certainly have to replace the I2C logic with SPI logic, as well as change the GPIO ports used.

**Comment by konimaru** [comment]
Ah, yes. I forgot but it shouldn't be too much effort.

**Comment by cspang1** [comment]
Nah, especially with a great deal of SPI logic already available in the Propeller library.

**Comment by cspang1** [comment]
Will be satisfied w/ HAM.
