### ISSUE TITLE
Optimize cog-hub scanline buffer transfer

### ISSUE THREAD

**Issue by konimaru** [cspang1/JCAP#77]
```
        ' Write scanline buffer to video buffer in Main RAM
write   wrlong          slbuff+0, curvb         ' If so, write scanline buffer to Main RAM video buffer
        add             write,  d0              ' Increment scanline buffer memory location
        add             curvb,  #4              ' Increment video buffer memory location
        djnz            index,  #write          ' Repeat for all scanline segments
```
Something like [this](https://forums.parallax.com/discussion/comment/1108886/#Comment_1108886) would certainly be faster (and doesn't even use counters, although it started counter based).

**Comment by konimaru** [comment]
The cure loop contains 6 insn and we need 3 for setup (2x **movd**, 1x hub location with magic marker).

**Comment by cspang1** [comment]
Wow that's some impressive bit magic! Implementing...

**Comment by cspang1** [comment]
Satisfied by 927afe3df0f42e4ff23c15722e2fbdbc5b1e0691

Thanks again @konimaru!
