### ISSUE TITLE
Remove delays in input.spin

### ISSUE THREAD

**Issue by cspang1** [cspang1/JCAP#9]
Delays are redundant due to the fact that each instruction takes at least 4 clock cycles, and with 2 instructions to toggle, that's **1 second/(80,000,000/4/2) = 100 nanoseconds** minimum between pin toggles, well above the timing requirements for the 74HC165.

**Comment by cspang1** [comment]
Satisfied by commit 5af2eee

**Comment by konimaru** [comment]
FWIW, this only applies to pure s/w solutions. Using the counters gives you finer granularity.
